# Generated by Django 3.2.20 on 2023-09-14 04:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neww', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neww',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
