# Generated by Django 3.2.20 on 2023-09-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neww', '0002_neww_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='neww',
            name='news_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
